# Generated by Django 2.1.3 on 2018-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181121_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='document',
            field=models.FileField(default='settings.DEFAULT_FILE_STORAGE', upload_to='documents/blogs'),
        ),
    ]
