# Generated by Django 2.1.3 on 2018-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='document',
            field=models.FileField(upload_to='documents/blogs'),
        ),
    ]
