# Generated by Django 2.1.3 on 2018-11-23 02:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181122_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49),
        ),
    ]
